openapi: 3.2.0
info:
  title: Oper Credits Metrics API
  version: ''
tags:
- name: Metrics
paths:
  /metrics/certs-expiration:
    get:
      operationId: metrics_certs_expiration_retrieve
      responses:
        '200':
          description: No response body
      security:
      - jwtAuth: []
      tags:
      - Metrics
      summary: Metrics certs expiration retrieve
      x-summary-source: derived
components:
  securitySchemes:
    jwtAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
