openapi: 3.2.0
info:
  title: Oper Credits Integrations API
  version: ''
tags:
- name: Integrations
paths:
  /api/integrations/allowed-integrators/:
    get:
      operationId: api_integrations_allowed_integrators_list
      parameters:
      - in: query
        name: integrator_type
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Integrator'
                type: array
          description: ''
      security:
      - jwtAuth: []
      tags:
      - Integrations
      summary: Api integrations allowed integrators list
      x-summary-source: derived
  /api/integrations/allowed-integrators/{id}/:
    get:
      operationId: api_integrations_allowed_integrators_retrieve
      parameters:
      - description: A unique integer value identifying this Integrator.
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Integrator'
          description: ''
      security:
      - jwtAuth: []
      tags:
      - Integrations
      summary: Api integrations allowed integrators retrieve
      x-summary-source: derived
components:
  schemas:
    Integrator:
      properties:
        credit_provider:
          type:
          - integer
          - 'null'
        documents_push_email:
          format: email
          readOnly: true
          type: string
        external_url:
          format: uri
          readOnly: true
          type: string
        id:
          readOnly: true
          type: integer
        integrator_type:
          readOnly: true
          type: integer
        name:
          maxLength: 128
          type: string
        number_of_transfer_rounds:
          readOnly: true
          type:
          - integer
          - 'null'
        version:
          default: ''
          readOnly: true
          type: string
        webhook:
          readOnly: true
          type:
          - integer
          - 'null'
      required:
      - documents_push_email
      - external_url
      - id
      - integrator_type
      - name
      - number_of_transfer_rounds
      - version
      - webhook
      type: object
  securitySchemes:
    jwtAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
