openapi: 3.0.3
info:
  title: Oper Credits Agent Documents API
  version: "1.0"
tags:
- name: Agent Documents
paths:
  /api/agent-documents/:
    get:
      operationId: api_agent_documents_list
      parameters:
      - description: A page number within the paginated result set.
        in: query
        name: page
        required: false
        schema:
          type: integer
      - description: Number of results to return per page.
        in: query
        name: page_size
        required: false
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedAgentDocumentList'
          description: ''
      security:
      - jwtAuth: []
      tags:
      - Agent Documents
    post:
      operationId: api_agent_documents_create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgentDocumentUpload'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AgentDocumentUpload'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AgentDocumentUpload'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentDocumentUpload'
          description: ''
      security:
      - jwtAuth: []
      tags:
      - Agent Documents
  /api/agent-documents/{id}/:
    get:
      operationId: api_agent_documents_retrieve
      parameters:
      - description: A unique integer value identifying this Agent document.
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentDocument'
          description: ''
      security:
      - jwtAuth: []
      tags:
      - Agent Documents
components:
  schemas:
    DocumentStatus:
      description: Can be managed at /resources/document-status
      properties:
        definition:
          type: string
        id:
          type: integer
        order:
          readOnly: true
          type: integer
      required:
      - definition
      - id
      - order
      type: object
    AgentDocument:
      properties:
        document:
          $ref: '#/components/schemas/AgentDocumentSignedUrl'
        id:
          readOnly: true
          type: integer
        uploaded_by:
          format: email
          readOnly: true
          title: Email address
          type: string
      required:
      - id
      - uploaded_by
      type: object
    AgentDocumentUpload:
      properties:
        document:
          $ref: '#/components/schemas/AgentDocumentSignedUrl'
        file:
          format: uri
          type: string
          writeOnly: true
        id:
          readOnly: true
          type: integer
        uploaded_by:
          format: email
          readOnly: true
          title: Email address
          type: string
      required:
      - file
      - id
      - uploaded_by
      type: object
    AgentDocumentSignedUrl:
      properties:
        configuration_id:
          format: uuid
          type: string
        created:
          format: date-time
          readOnly: true
          title: Creation date and time
          type: string
        created_object_id:
          nullable: true
          readOnly: true
          type: integer
        document_type:
          $ref: '#/components/schemas/DocumentType'
        file_name:
          type: string
        id:
          readOnly: true
          type: integer
        integrator_transfer_rounds:
          items:
            additionalProperties: {}
            type: object
          readOnly: true
          type: array
        is_sent:
          type: boolean
        is_signed:
          type: boolean
        last_modified:
          format: date-time
          readOnly: true
          title: Modification date and time
          type: string
        link_id:
          nullable: true
          readOnly: true
          type: integer
        mime_type:
          readOnly: true
          type: string
        object_file_name:
          maxLength: 256
          type: string
        object_id:
          format: uuid
          type: string
        oper_reference:
          format: uuid
          readOnly: true
          type: string
        sha256_hash:
          maxLength: 64
          type: string
        signed_date:
          format: date-time
          nullable: true
          type: string
        status:
          allOf:
          - $ref: '#/components/schemas/DocumentStatus'
          readOnly: true
        url:
          readOnly: true
          type: string
        version:
          readOnly: true
          type: string
      required:
      - created
      - created_object_id
      - document_type
      - file_name
      - id
      - integrator_transfer_rounds
      - last_modified
      - link_id
      - mime_type
      - oper_reference
      - status
      - url
      - version
      type: object
    PaginatedAgentDocumentList:
      properties:
        count:
          example: 123
          type: integer
        next:
          example: http://api.example.org/accounts/?page=4
          format: uri
          nullable: true
          type: string
        previous:
          example: http://api.example.org/accounts/?page=2
          format: uri
          nullable: true
          type: string
        results:
          items:
            $ref: '#/components/schemas/AgentDocument'
          type: array
      required:
      - count
      - results
      type: object
    DocumentType:
      description: Can be managed at /resources/document-type
      properties:
        add_to_handover_letter:
          type: boolean
        allows_generation:
          type: boolean
        append_file_version:
          type: boolean
        can_be_added_manually_as_informative_document:
          type: boolean
        definition:
          type: string
        document_generation_configuration: {}
        id:
          type: integer
        is_informative:
          type: boolean
        is_proof_to_sign:
          type: boolean
        order:
          readOnly: true
          type: integer
      required:
      - definition
      - id
      - order
      type: object
  securitySchemes:
    jwtAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
