openapi: 3.2.0
info:
  title: Oper Credits Pricing API
  version: ''
tags:
- name: Pricing
paths:
  /api/pricing/excel-pricer/download-template/:
    get:
      operationId: api_pricing_excel_pricer_download_template_retrieve
      responses:
        '200':
          description: No response body
      security:
      - jwtAuth: []
      tags:
      - Pricing
      summary: Api pricing excel pricer download template retrieve
      x-summary-source: derived
components:
  securitySchemes:
    jwtAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
