openapi: 3.0.3
info:
  title: Oper Credits Agent Documents Forgot Password API
  version: ''
tags:
- name: Forgot Password
paths:
  /api/forgot-password/:
    post:
      description: 'API view to create a unique link for the user to change his or her password.

        Only post is allowed.

        If the user is not present, no warning will be given.'
      operationId: api_forgot_password_create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotPassword'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ForgotPassword'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ForgotPassword'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForgotPassword'
          description: ''
      tags:
      - Forgot Password
components:
  schemas:
    ForgotPassword:
      properties:
        email:
          format: email
          type: string
      required:
      - email
      type: object
  securitySchemes:
    jwtAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
