openapi: 3.0.3
info:
  title: Oper Credits Agent Documents Check Reset Password API
  version: ''
tags:
- name: Check Reset Password
paths:
  /api/check-reset-password/:
    post:
      description: This check verifies whether the reset password token is valid.
      operationId: api_check_reset_password_create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckResetPassword'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CheckResetPassword'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CheckResetPassword'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckResetPassword'
          description: ''
      tags:
      - Check Reset Password
components:
  schemas:
    CheckResetPassword:
      description: This serializer checks whether the token is valid
      properties:
        token:
          type: string
      required:
      - token
      type: object
  securitySchemes:
    jwtAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
