openapi: 3.2.0
info:
  title: Oper Credits Products API
  version: ''
tags:
- name: Products
paths:
  /api/products/:
    get:
      operationId: api_products_list
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/StaticProduct'
                type: array
          description: ''
      security:
      - jwtAuth: []
      tags:
      - Products
      summary: Api products list
      x-summary-source: derived
components:
  schemas:
    StaticProduct:
      properties:
        products:
          readOnly: true
          type: string
      required:
      - products
      type: object
  securitySchemes:
    jwtAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
