openapi: 3.2.0
info:
  title: Oper Credits Health API
  version: ''
tags:
- name: Health
paths:
  /api/health/:
    get:
      description: This View simply return a 200 for diagnostics purposes.
      operationId: api_health_retrieve
      responses:
        '200':
          description: No response body
      security:
      - jwtAuth: []
      tags:
      - Health
      summary: Api health retrieve
      x-summary-source: derived
components:
  securitySchemes:
    jwtAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
