openapi: 3.2.0
info:
  title: Oper Credits Bank Release Policy API
  version: ''
tags:
- name: Bank Release Policy
paths:
  /api/bank-release-policy/:
    get:
      operationId: api_bank_release_policy_retrieve
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BankReleasePolicy'
          description: ''
      security:
      - jwtAuth: []
      tags:
      - Bank Release Policy
      summary: Api bank release policy retrieve
      x-summary-source: derived
components:
  schemas:
    Language:
      description: Can be managed at /resources/language
      properties:
        definition:
          type: string
        id:
          type: integer
        order:
          readOnly: true
          type: integer
      required:
      - definition
      - id
      - order
      type: object
    BankReleasePolicy:
      properties:
        configuration_id:
          format: uuid
          type: string
        content:
          type: string
        language:
          $ref: '#/components/schemas/Language'
        tenant:
          type:
          - integer
          - 'null'
        title:
          maxLength: 128
          type: string
      required:
      - content
      - language
      - title
      type: object
  securitySchemes:
    jwtAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
