openapi: 3.2.0
info:
  title: Oper Credits Model Fields API
  version: ''
tags:
- name: Model Fields
paths:
  /api/model-fields/:
    get:
      operationId: api_model_fields_retrieve
      responses:
        '200':
          description: No response body
      security:
      - jwtAuth: []
      tags:
      - Model Fields
      summary: Api model fields retrieve
      x-summary-source: derived
components:
  securitySchemes:
    jwtAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
