openapi: 3.0.3
info:
  title: Oper Credits Agent Documents Reset Password API
  version: "1.0"
tags:
- name: Reset Password
paths:
  /api/reset-password/:
    post:
      description: 'API view to actually change the password of the user.

        Only post is allowed.

        Security is checked by comparing the JWT secret with the current hashed password of the user.'
      operationId: api_reset_password_create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPassword'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ResetPassword'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ResetPassword'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResetPassword'
          description: ''
      tags:
      - Reset Password
components:
  schemas:
    ResetPassword:
      description: 'This serializer will update the password to a new password if:

        * They match

        * The token is verified in regards to expiration date, signing code and user id

        * The password is strong enough'
      properties:
        bank_release_policy_accepted:
          default: false
          type: boolean
          writeOnly: true
        contact_policy_accepted:
          default: false
          type: boolean
          writeOnly: true
        gdpr_policy_accepted:
          default: false
          type: boolean
          writeOnly: true
        new_password_one:
          maxLength: 128
          type: string
          writeOnly: true
        new_password_two:
          maxLength: 128
          type: string
          writeOnly: true
        privacy_policy_accepted:
          default: false
          type: boolean
          writeOnly: true
        terms_and_conditions_accepted:
          default: false
          type: boolean
          writeOnly: true
        token:
          type: string
          writeOnly: true
      required:
      - new_password_one
      - new_password_two
      - token
      type: object
  securitySchemes:
    jwtAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
